name: Run Tests

on:
  push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Demo Test
        uses: action/checkout@v1
      - name: Setup Node
        uses: action/setup-node@v1
        with:
          node-version: 16.18
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test