name: Run Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Demo Test
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: node --test
