name: ESLint Check

on:
  pull_request:
    branches:
      - testcases
  push:
    branches:
      - testcases

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello World
        run: echo "Hello World"

      - name: Install dependencies
        run: npm install # Installs all dependencies from package.json

      - name: Run Tests
        run: npm test